Feature/#7 qualification criteria
SOA-DevTeam/MyMovie pull request #8
Opened 2020-11-06 22:58 UTC by kevin9907

2020-11-06 23:04 UTC, kgonzalez712 requested changes
Eliminar los console

2020-11-06 23:23 UTC, ljcorraless requested changes

2020-11-06 23:23 UTC, ljcorraless commented on MyMovieServer/Controllers/RecommendationFilterController.cs
> +            LogicaFiltrosRecomendacion get = new LogicaFiltrosRecomendacion();
Usá una instancia global de la clase de lógica

2020-11-06 23:23 UTC, ljcorraless commented on MyMovieServerTests/Controllers/ControladorFiltrosRecomendacionTests.cs
> +            Console.WriteLine(controller.GetGen()[0].Genero1);
Las pruebas es mejor hacerlas con assert.Equals(respuestaObtenida, respuestaEsperada)

2020-11-06 23:58 UTC, ljcorraless approved these changes
Todo gucci

2020-11-07 00:08 UTC, kgonzalez712 approved these changes

2020-11-07 00:09 UTC, merged